### ISSUE TITLE
Support non-root user

### ISSUE THREAD

**Issue by ywk253100** [paketo-buildpacks/jammy-tiny-stack#147]
A non-root user should be created inside the base image and the home directory and its corresponding permission should also be taken care of. Without this, the program that tries to write files to the home directory(because of no entry in `/etc/passwd`, the home directory falls back to `/`) will fail.

**Comment by robdimsdale** [comment]
How are you trying to use this stack?

Within the context of buildpacks, we create a `cnb` user with non-root permissions. That's the only supported use-case for this stack.

**Comment by ywk253100** [comment]
I use `paketobuildpacks/run-jammy-tiny:latest` as the base image directly, I don't see any valid non-root user in https://github.com/paketo-buildpacks/jammy-tiny-stack/blob/main/stack/run/files/passwd

**Comment by robdimsdale** [comment]
The `cnb` user is created [as part of the stack creation process](https://github.com/paketo-buildpacks/jam/blob/3c822ffe5ce5e416f6da897e4bfde16591418103/internal/ihop/user_layer_creator.go#L66).


We can see the `cnb` user does not have root permissions by extracting the filesystem:
```
docker create paketobuildpacks/run-jammy-tiny:latest noop
docker export <container-id-from-docker-create> -o /tmp/run-jammy-tiny-fs.tar
cd /tmp
mkdir run-jammy-tiny-fs
cd run-jammy-tiny-fs/
tar -xvf ../run-jammy-tiny-fs.tar
```

And then looking at `/etc/passwd`:
```
cat ./etc/passwd
root:x:0:0:root:/root:/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/sbin/nologin
cnb:x:1002:1000::/home/cnb:/sbin/nologin
```

Did you observe something different on the running container?

**Comment by ywk253100** [comment]
Thanks @robdimsdale, that's exactly what we need. I'm closing the issue.
