### ISSUE TITLE
Extract Alert on Failure into an Action

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/jammy-tiny-stack#5]
The Alert on Failure job in the release pipeline uses inline bash scripting to hit the Github API. We should extract this logic into an action that can be reused across Paketo repositories. It's possible that an action already exists for this that we can reuse.

The action will probably need to accept parameters:
- issue label: the label the action should search for when determining if a failure issue already exists
- title: the title of the issue to file
- url: the URL of the failing run to link to
- repo: the repository where the issue should be filed
- token: Github token to use for creating the issue

**Comment by sophiewigmore** [comment]
Related: https://github.com/paketo-buildpacks/github-config/issues/459
